USE [master]
GO

CREATE DATABASE [ApiTestDB] CONTAINMENT = NONE ON  PRIMARY 
( NAME = N'ApiTestDB', FILENAME = N'C:\...\ApiTestDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON ( NAME = N'ApiTestDB_log', FILENAME = N'C:\...\ApiTestDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ApiTestDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [ApiTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ApiTestDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ApiTestDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ApiTestDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ApiTestDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ApiTestDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ApiTestDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ApiTestDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ApiTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ApiTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ApiTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ApiTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ApiTestDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ApiTestDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ApiTestDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ApiTestDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ApiTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ApiTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ApiTestDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ApiTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ApiTestDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ApiTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ApiTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ApiTestDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ApiTestDB] SET  MULTI_USER 
GO
ALTER DATABASE [ApiTestDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ApiTestDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ApiTestDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ApiTestDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ApiTestDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ApiTestDB] SET  READ_WRITE 
GO

USE [master]
GO

CREATE DATABASE [ApiEvaluateDB] CONTAINMENT = NONE ON  PRIMARY 
( NAME = N'ApiEvaluateDB', FILENAME = N'C:\...\ApiEvaluateDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON ( NAME = N'ApiEvaluateDB_log', FILENAME = N'C:\...\ApiEvaluateDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ApiEvaluateDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [ApiEvaluateDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ApiEvaluateDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ApiEvaluateDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ApiEvaluateDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ApiEvaluateDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ApiEvaluateDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ApiEvaluateDB] SET  MULTI_USER 
GO
ALTER DATABASE [ApiEvaluateDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ApiEvaluateDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ApiEvaluateDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ApiEvaluateDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ApiEvaluateDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ApiEvaluateDB] SET  READ_WRITE 
GO
