USE [ApiTestDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON
GO
;

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestFirstTest')
BEGIN
	DROP table dbo.ApiTestFirstTest
end
go

/* HISTORY   
	12/05/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
CREATE 
TABLE 
[dbo].[ApiTestFirstTest]
(
	FirstTestID 
INT 
IDENTITY(1, 1) 
NOT NULL, -- IDENTITY COLUMN
	Selected [BIT] NOT NULL DEFAULT(0), 
	CreatedDate [DATETIME] NOT NULL DEFAULT(GETDATE()), UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()), [UpdatedBy] VARCHAR(50) NOT NULL CONSTRAINT FK_FirstTestID_FirstTestUpdatedBy_UsersUserName REFERENCES dbo.ApiTestUser (UserName),
	CONSTRAINT PK_FirstTest PRIMARY KEY CLUSTERED (FirstTestID ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
