USE [ApiTestDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestThirdTest')
BEGIN
	DROP table dbo.ApiTestThirdTest
end
go

/* HISTORY   
	12/05/2016 - dsen 
*/ 	
/* DESCRIPTION  	...*/
CREATE TABLE dbo.ApiTestThirdTest(ThirdTestID INT IDENTITY(1, 1) NOT NULL, RangeFrom DATETIME NULL, RangeTo DATETIME NULL, CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedBy VARCHAR(50) NOT NULL CONSTRAINT FK_ThirdTestUpdatedBy_UserUserName REFERENCES dbo.ApiTestUser (UserName)) 
GO
