USE [ApiEvaluateDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestFifthTest')
BEGIN
	DROP table dbo.ApiTestFifthTest
end
go

/* HISTORY   
	12/14/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
create table dbo.ApiTestFifthTest
(
	FifthTestID INT NOT NULL CONSTRAINT UC_FifthTest_FifthTestID UNIQUE(FifthTestID),
	Name VARCHAR(64) NOT NULL, 
	Rank int NOT NULL, -- order 
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	CreatedBy VARCHAR(50) NOT NULL CONSTRAINT FK_FifthTestCreatedBy_UserUserName REFERENCES dbo.ApiTestUser (UserName),
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedBy VARCHAR(50) NOT NULL CONSTRAINT FK_FifthTestUpdatedBy_UserUserName REFERENCES dbo.ApiTestUser (UserName),
	CONSTRAINT PK_FifthTests PRIMARY KEY CLUSTERED (FifthTestID ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
