USE ApiEvaluateDB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestUser')
BEGIN
	DROP table dbo.ApiTestUser
end
go

/* HISTORY   
	12/14/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
create table dbo.ApiTestUser
(
	UserID INT IDENTITY(1, 1) NOT NULL,
	UserName VARCHAR(50) NOT NULL, 
	[Rank] int NOT NULL, 
	CONSTRAINT PK_User PRIMARY KEY CLUSTERED (UserName ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
