USE [ApiEvaluateDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON;
GO
SET ANSI_PADDING ON
GO
;

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestMainTest')
BEGIN
	DROP table [dbo].ApiTestMainTest
end
go

/* HISTORY   
	12/05/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
CREATE 
TABLE 
[dbo].ApiTestMainTest
(
	MainTestID 
INT 
IDENTITY(1, 1) 
NOT NULL, -- IDENTITY COLUMN
	Selected [BIT] NOT NULL DEFAULT(0), 
	UpdatedOn DATETIME NOT NULL
		 DEFAULT(GETDATE()), UpdatedBy VARCHAR(50) NOT NULL CONSTRAINT FK_MainTestUpdatedBy_UserUserName REFERENCES dbo.ApiTestUser (UserName),
	CONSTRAINT PK_MainTest PRIMARY KEY CLUSTERED (MainTestID ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 





--SELECT * FROM dbo.ApiTestMainTest