USE [ApiEvaluateDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ApiTestFourthTest')
BEGIN
	DROP table dbo.ApiTestFourthTest
end
go

/* HISTORY   
	12/14/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
create table dbo.ApiTestFourthTest
(
	FourthTestID INT IDENTITY(1, 1) NOT NULL,
	TypeID int NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedBy VARCHAR(50) NOT NULL CONSTRAINT FK_FourthTestUpdatedBy_UsersUserName REFERENCES dbo.ApiTestUser (UserName),
	CONSTRAINT PK_FourthTest PRIMARY KEY CLUSTERED (FourthTestID ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

--DROP TABLE dbo.FourthTest
--SELECT * FROM dbo.FourthTest
