USE [ApiTestDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'sen' AND TABLE_NAME = 'ApiTestSecondTest')
BEGIN
	DROP table sen.ApiTestSecondTest
end
go

/* HISTORY   
	12/29/2016 - dsen 
*/ 	
/* DESCRIPTION  
	...
*/
create table 
[sen].[ApiTestSecondTest]
(
	[SecondTestID] INT IDENTITY(1, 1) NOT NULL,        
	TestText VARCHAR(1024) NOT NULL,	TestManifest TEXT NOT NULL,	IsScheduled BIT NOT NULL,
	ScheduledDate DATETIME NOT NULL DEFAULT(GETDATE()),
	CONSTRAINT PK_SecondTest PRIMARY KEY CLUSTERED (SecondTestID ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO
